server:
  port: 9000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    allow-redirects: false
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  config:
    activate:
      on-profile: local
  main:
    web-application-type: reactive
  application:
    name: VettGatewayServer
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - 'http://localhost:5173'
              - 'https://web-vett-frontend-ss7z32llwmafmaz.sel5.cloudtype.app'
              - 'https://port-0-vett-admin-ss7z32llwmafmaz.sel5.cloudtype.app'
            allowCredentials: true
            allowedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - PATCH
              - OPTIONS
      routes:
        - id: vett-auth-service
          uri: lb://VETT-AUTH-SERVER
          predicates:
            - Path=/auth/**, /admin/auth/**, /oauth2/**
        - id: vett-place-service
          uri: lb://VETT-PLACE-SERVER
          predicates:
            - Path=/place/**, /admin/place/**
        - id: vett-chat-service
          uri: lb://VETT-CHAT-SERVER
          predicates:
            - Path=/chat/**, /admin/chat/**, /sub/**, /ws, /pub/**

jwt:
  secret: ${JWT_SECRET}
admin:
  secret: ${ADMIN_SECRET}
  header:
    name: ${ADMIN_HEADER}

